---
all:
  hosts:
    localhost:
      ansible_connection: local

    pi4b:
      ansible_host: pi4b
      ansible_user: pi
      ansible_python_interpreter: /usr/bin/python3
      portainer_host: pi4b

    pi4:
      ansible_host: pi4
      ansible_user: pi
      ansible_python_interpreter: /usr/bin/python3
      portainer_host: pi4b

  children:
    swarm_manager:
      hosts:
        pi4b
    swarm_nodes:
      hosts:
        pi4
    nexus:
      hosts:
        pi4:
