---
- name: Create /srv/nexus/ directory with specific ownership
  become: true
  file:
    path: /srv/nexus/
    state: directory
    owner: "{{ home_user }}"
    group: "{{ home_user | default(home_user) }}"
    mode: '0755'