# Delete a Docker stack
#
# Expected variables:
# - portainer_stack_id:         (integer) ID of the stack
# - portainer_endpoint_id:      (integer) The ID of the Portainer endpoint where the stack will be deployed
#

- name: Delete stack "{{ stack_name }}" with id "{{ portainer_stack_id }} at endpoint "{{ portainer_endpoint_id }}"
  uri:
    validate_certs: false
    status_code: 204
    url: "{{ portainer_api_url }}/stacks/{{ portainer_stack_id }}?endpointId={{ portainer_endpoint_id }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ portainer_token }}"
  register: deploy_stack_result
