version: '3.8'

services:
  keycloak:
    image: keycloak/keycloak:26.3
    secrets:
      - cert_key
      - cert
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-keycloak}
      KC_DB: ${KD_DB:-postgres}
      KC_DB_URL: ${KC_DB_URL:-jdbc:postgresql://postgres:5432/keycloak}
      KC_DB_USERNAME: ${KC_DB_USERNAME:-keycloak}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD:-keycloak}
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_PROXY: edge
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HTTPS_CERTIFICATE_FILE: /run/secrets/cert
      KC_HTTPS_CERTIFICATE_KEY_FILE: /run/secrets/cert_key
    networks:
      - home-net
    command:
      - start
      - --hostname=${KC_HOSTNAME}
      - --hostname-strict=false
    ports:
      - "${KC_PORT}:8443"
    healthcheck:
      test: ["CMD-SHELL", "exec /bin/sh -c 'timeout 2 cat < /dev/null >/dev/null 2>&1 || exit 0'"]
      interval: 10s
      timeout: 5s
      retries: 10
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.keycloak == true

secrets:
  cert:
    external: true
  cert_key:
    external: true

networks:
  home-net:
    external: true