version: "3.8"

services:
  nexus:
    image: "sonatype/nexus3:3.78.3"
    user: "${USER_UID}:${USER_GID}"
    environment:
      NEXUS_CONTEXT: "/"
    volumes:
       - /srv/nexus/data:/nexus-data
    ports:
      - "8081:8081"
    networks:
      - home-net
    deploy:
      placement:
        constraints:
          - node.labels.nexus == true

networks:
  home-net:
    external: true