version: "3.9"

services:
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
      - "8443:8443"
    secrets:
      - cert_key
      - cert
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
        mode: 0444
    networks:
      - home-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.nginx == true

configs:
  nginx_config:
    external: true

secrets:
  cert:
    external: true
  cert_key:
    external: true

networks:
  home-net:
    external: true
