---
#vars:
#  prometheus_version: "3.5.0"
#  prometheus_arch_map:
#    x86_64: amd64
#    aarch64: arm64
- name: Create prometheus user
  ansible.builtin.user:
    name: prometheus
    shell: /usr/sbin/nologin
    system: yes
    create_home: no

- name: Check if "{{ prometheus_base_dir }}" exists
  ansible.builtin.stat:
    path: "{{ prometheus_base_dir }}/prometheus"
  register: prometheus_dir

- name: Stop play if Prometheus is already installed
  ansible.builtin.meta: end_play
  when: prometheus_dir.stat.exists


- name: Detect system architecture
  ansible.builtin.command: uname -m
  register: arch_raw
  changed_when: false

- name: Map architecture to Prometheus naming
  set_fact:
    prometheus_arch: "{{ prometheus_arch_map[arch_raw.stdout] | default(arch_raw.stdout) }}"

- name: Create Prometheus install dir
  ansible.builtin.file:
    path: "{{ prometheus_base_dir }}"
    state: directory
    mode: '0755'

- name: Download Prometheus tarball
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-{{ prometheus_arch }}.tar.gz"
    dest: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ prometheus_arch }}.tar.gz"
    mode: '0644'

- name: Extract Prometheus
  ansible.builtin.unarchive:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ prometheus_arch }}.tar.gz"
    dest: "/opt"
    owner: prometheus
    group: prometheus
    remote_src: true

- name: Rename extracted dir to prometheus
  ansible.builtin.command:
    cmd: "mv /{{ prometheus_base_dir }}/prometheus-{{ prometheus_version }}.linux-{{ prometheus_arch }} {{ prometheus_base_dir }}/prometheus"
  args:
    creates: "{{ prometheus_base_dir }}/prometheus"

- name: Remove tarball
  ansible.builtin.file:
    path: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ prometheus_arch }}.tar.gz"
    state: absent

- name: Get server primary IP
  ansible.builtin.command: hostname -I
  register: ip_output
  changed_when: true

- name: Configure prometheus.yml
  ansible.builtin.copy:
    dest: "{{ prometheus_base_dir }}/prometheus//prometheus.yml"
    mode: '0644'
    owner: prometheus
    group: prometheus
    content: |
      global:
        scrape_interval: 15s
      scrape_configs:
        - job_name: "node"
          static_configs:
            - targets: ["{{ ip_output.stdout.split()[0] }}:9100"]
