- name: Prepare grafana host
  hosts: database
  tasks:
    - name: Setup postgres on host
      include_role:
        name: grafana
        tasks_from: setup

- name: Deploy stack postgres via Portainer API
  hosts: localhost
  vars:
    stack_name: grafana
    portainer_endpoint_name: charger
    repositoryURL: "https://github.com/Buchtl/home-deployment.git"
    repositoryReferenceName: "{{ git_default_branch }}"
    composeFile: "stacks/grafana-stack.yml"
    stack_env:
      - name: "USER_UID"
        value: "{{ home_uid }}"
      - name: "USER_GID"
        value: "{{ home_gid }}"
      - name: "GRAFANA_ROLE_MAPPING"
        value: "contains(resource_access.grafana.roles, 'admin') && 'Admin' || contains(resource_access.grafana.roles, 'viewer') && 'Viewer'"
      - name: "GRAFANA_HOSTNAME"
        value: "pi4b"
      - name: "GRAFANA_PORT"
        value: "12443"
      - name: "KC_CLIENT_SECRET_GRAFANA"
        value: "p4ZufcYZsDMzFejfjU8AKhlFWO1267M5"
      - name: "KC_HOSTNAME"
        value: "pi4b"
      - name: "KC_PORT"
        value: "10443"
     
  tasks:
    - include_tasks: ../roles/portainer/tasks/authenticate.yml
    - include_tasks: ../roles/portainer/tasks/endpoint_id.yml
    - include_tasks: ../roles/portainer/tasks/deploy_stack.yml
